// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3550.testRymaNehela;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainDriveright;
    public static SpeedController drivetrainDriveleft;
    public static RobotDrive drivetrainRobotDrive21;
    public static SpeedController lanceurMoteurLanceur;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainDriveright = new Talon(3);
        LiveWindow.addActuator("Drive train", " Driveright", (Talon) drivetrainDriveright);
        
        drivetrainDriveleft = new Talon(2);
        LiveWindow.addActuator("Drive train", "Driveleft", (Talon) drivetrainDriveleft);
        
        drivetrainRobotDrive21 = new RobotDrive(drivetrainDriveleft, drivetrainDriveright);
        
        drivetrainRobotDrive21.setSafetyEnabled(true);
        drivetrainRobotDrive21.setExpiration(0.1);
        drivetrainRobotDrive21.setSensitivity(0.5);
        drivetrainRobotDrive21.setMaxOutput(1.0);

        lanceurMoteurLanceur = new Talon(1);
        LiveWindow.addActuator("Lanceur", "MoteurLanceur", (Talon) lanceurMoteurLanceur);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
